/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("MinecraftCosmosInfra.kotlin-lambda-conventions")
    id("com.github.johnrengelman.shadow") version "7.0.0"
}

dependencies {
    implementation("com.amazonaws:aws-lambda-java-core:1.2.1")
}
